language: c

notifications:
  email: false

before_script:
# travis has changed to 64-bit and we require 32-bit compatibility libraries
  - sudo apt-get update
  # clang
  - "sudo apt-get -qq install gcc-arm-linux-gnueabi gcc-arm-linux-gnueabihf || true"

script:
  - make

env:
  - CC='arm-linux-gnueabi-gcc'
  - CC='arm-linux-gnueabihf-gcc'
